# Generated by Django 5.0.2 on 2024-04-18 03:20

import jobSite.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job_data',
            fields=[
                ('job_Id', models.AutoField(primary_key=True, serialize=False)),
                ('job_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('job_desc', models.CharField(max_length=255)),
                ('job_photo', models.ImageField(blank=True, null=True, upload_to=jobSite.models.user_directory_path, verbose_name='')),
            ],
            options={
                'db_table': 'jobs',
            },
        ),
    ]
